import re
with open('app/src/main/java/com/example/ui/screens/ReportsScreen.kt', 'r') as f:
    content = f.read()

# Replace any word character followed immediately by "import " or "package " or "@"
content = content.replace('screensimport', 'screens\nimport')
content = content.replace('Shapeimport', 'Shape\nimport')
content = content.replace('Dialogimport', 'Dialog\nimport')
content = content.replace('Contextimport', 'Context\nimport')
content = content.replace('Toastimport', 'Toast\nimport')
content = content.replace('Resultimport', 'Result\nimport')
content = content.replace('Contractsimport', 'Contracts\nimport')
content = content.replace('Sizeimport', 'Size\nimport')
content = content.replace('Springimport', 'Spring\nimport')
content = content.replace('springimport', 'spring\nimport')
content = content.replace('clickableimport', 'clickable\nimport')
content = content.replace('FlowRowimport', 'FlowRow\nimport')
content = content.replace('Infoimport', 'Info\nimport')

content = content.replace('.*import', '.*\nimport')
content = content.replace('Columnimport', 'Column\nimport')
content = content.replace('Rowimport', 'Row\nimport')
content = content.replace('itemsimport', 'items\nimport')
content = content.replace('Iconsimport', 'Icons\nimport')
content = content.replace('ArrowBackimport', 'ArrowBack\nimport')
content = content.replace('.*@', '.*\n@')
content = content.replace('Colorimport', 'Color\nimport')
content = content.replace('LocalContextimport', 'LocalContext\nimport')
content = content.replace('Weightimport', 'Weight\nimport')
content = content.replace('dpimport', 'dp\nimport')
content = content.replace('spimport', 'sp\nimport')
content = content.replace('Lifecycleimport', 'Lifecycle\nimport')
content = content.replace('StoreViewModelimport', 'StoreViewModel\nimport')
content = content.replace('Currencyimport', 'Currency\nimport')
content = content.replace('Qtyimport', 'Qty\nimport')
content = content.replace('Chartimport', 'Chart\nimport')
content = content.replace('Excelimport', 'Excel\nimport')
content = content.replace('launchimport', 'launch\nimport')
content = content.replace('Formatimport', 'Format\nimport')
content = content.replace('Calendarimport', 'Calendar\nimport')
content = content.replace('Dateimport', 'Date\nimport')
content = content.replace('Locale@', 'Locale\n@')
content = content.replace('Localeimport', 'Locale\nimport')
content = content.replace('Modifierimport', 'Modifier\nimport')
content = content.replace('Alignmentimport', 'Alignment\nimport')
content = content.replace('compose.runtime.*import', 'compose.runtime.*\nimport')

# Or just use regex correctly
content = re.sub(r'([a-zA-Z*])import ', r'\1\nimport ', content)
content = re.sub(r'([a-zA-Z*])package ', r'\1\npackage ', content)
content = re.sub(r'([a-zA-Z*])@', r'\1\n@', content)

with open('app/src/main/java/com/example/ui/screens/ReportsScreen.kt', 'w') as f:
    f.write(content)
